### ISSUE TITLE
Add mocking feed from various sources

### ISSUE THREAD

**Issue by InDieTasten** [RicoBrase/mocking.rocks#3]
Would be nice to see a feed of twitter, reddit, so. messages, where somebody is currently mocking.

**Comment by RicoBrase** [comment]
Could you elaborate please?
Are you requesting embedding e.g. a twitter feed of a "#mocking" hashtag?

**Comment by InDieTasten** [comment]
I am envisioning a backend service, that continuously sifts trending messages for what looks like mocking text.

The backend should be able to detect it without the aid of a "#mocking" hashtag, as many users will not include it.

The newest popular tweets with mocking are displayed on the site.

It's a bit of work, but with a domain like mocking.rocks you have to do it justice :D

**Comment by RicoBrase** [comment]
Sounds like a separate project for me - I will consider this, but close it as "wontfix" here.
